---
title: "crime"
output: html_document
---

测试集报错问题：
https://github.com/tidymodels/recipes/issues/494
https://github.com/tidymodels/recipes/issues/627


```{r, message=FALSE}
library(tidymodels)
library(tictoc)
library(tidyverse)
library(lubridate)
library(skimr)
library(pryr)
library(embed)
```


```{r}
source("function.r")
```


```{r, message=FALSE}
# 读入数据
test <- read_csv("test.csv", col_names = TRUE)
test %>% head()
```


```{r}
# recipe前的预处理
set.seed(100)
test %>% 
  filter(complete.cases(.)) %>% 
  sample_n(size = 300000) %>% 
  rename(Primary_type = `Primary Type`, 
         Location_description = `Location Description`, 
         Community_area = `Community Area`,
         FBI_code = `FBI Code`) %>%
  separate(col = Date, into = c("Date", "Time", "AP"), sep = " ") %>% # 复杂处理放到recipe外处理
  mutate(Date = mdy(Date), Time = hms(Time)) %>% 
  mutate(Month = month(Date, label = FALSE),
         Wday = wday(Date, label = FALSE),
         Hour = if_else(AP == "PM", hour(Time) + 12, hour(Time))) %>% # recipe没有关于time的处理工具
  mutate(Block_type = str_split(Block, " ")) %>% 
  mutate(Block_type = sapply(Block_type, function(x) last(unlist(x)))) %>% 
  select(-c(V1, `Case Number`, IUCR, `X Coordinate`, `Y Coordinate`, `Updated On`, 
            Location, Block, Time, AP, Year)) %>% 
  mutate(across(c("Beat", "District", "Ward", "Community_area"), as.factor),
         across(where(is.character) | where(is.logical), as.factor),
         across(where(is.double) & !c("Latitude", "Longitude", "Date"), as.integer)) %>% 
  mutate(Arrest = fct_relevel(Arrest, "TRUE")) %>% 
  arrange(Date) -> test_sample

# 查看结果
test_sample %>% head()
dim(test_sample)
glimpse(test_sample)
object_size(test_sample)
levels(test_sample$Arrest)

# 删除对象
rm(test)
gc()
```

```{r}
# 看因变量情况：重抽样没有用在测试集上
train_glm_ds_prep <- prep(train_glm_ds_rec, training = train_sample)
train_glm_ds_bake <- bake(train_glm_ds_prep, new_data = NULL)
test_bake <- bake(train_glm_ds_prep, new_data = test_sample)
```


```{r}
train_glm_ds_bake
train_glm_ds_bake %>% distinct(Primary_type) %>% arrange(Primary_type)
train_sample %>% filter(ID == 5965298)
```


```{r}
test_sample %>% filter(Primary_type == "CONCEALED CARRY LICENSE VIOLATION")
test_sample %>% filter(Primary_type == "HUMAN TRAFFICKING")
test_sample %>% filter(Primary_type == "NON-CRIMINAL")
test_sample %>% filter(Primary_type == "NON - CRIMINAL")
test_bake %>% filter(ID == 9541012)
test_bake %>% filter(ID == 9953754)
test_bake %>% filter(ID == 8602092)
test_bake %>% filter(ID == 9284607)
```



```{r}
setdiff(levels(test_sample$Primary_type), levels(train_sample$Primary_type))
```


```{r}
# 预测结果，将结果放在一个数据框中
rf_wf_final_fit <- read_rds("rf_wf_final_fit_new.rds")
rf_wf_pred_prob <- rf_wf_final_fit %>% predict(test_sample, type = "prob") # 预测概率
rf_wf_pred_class <- rf_wf_final_fit %>% predict(test_sample)               # 预测类别
rf_wf_pred_truth <- bind_cols(
  rf_wf_pred_prob %>% select(.pred_TRUE), 
  rf_wf_pred_class %>% select(.pred_class),
  test_sample %>% select(Arrest)) %>% 
  rename(pred_prob = .pred_TRUE, 
         pred_class = .pred_class, 
         truth = Arrest)
rf_wf_pred_truth
```


```{r}
# 混淆矩阵
rf_wf_pred_truth %>% count(pred_class)
rf_wf_pred_truth %>% count(truth)
conf_mat(data = rf_wf_pred_truth, truth = truth, estimate = pred_class)
accuracy(data = rf_wf_pred_truth, truth = truth, estimate = pred_class)
```


```{r}
# roc
levels(rf_wf_pred_truth$truth) # 注意正样本是第几个
roc_auc(data = rf_wf_pred_truth, truth = truth, estimate = pred_prob, event_level = "first")
two_class_curve <- roc_curve(rf_wf_pred_truth, truth = truth, estimate = pred_prob, event_level = "first")
two_class_curve
autoplot(two_class_curve)
```


